services:
  database:
    image: percona/percona-server-mongodb:8.0.19-7
    ports:
      - ${MONGO_PORT:-27017}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOTUSER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOTPASSWORD:-admin}
  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans
      - "4317:4317"
      - "4318:4318"
